# Generated by Django 5.1.1 on 2024-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_inmuebles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="arrendador",
            name="mail",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="arrendatario",
            name="mail",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
